### ISSUE TITLE
Watershed_Labeler not working in second computer

### ISSUE THREAD

**Issue by auesro** [KumarLabJax/MouseTrackingExtras#1]
So as I said [here](https://github.com/KumarLabJax/MouseTracking/issues/1#issuecomment-493984932) , I am able to build the labeler with g++ no issues. It opens, it watersheds, the terminal reports saving of the files...however the 3 folders are empty.

Very strange given I managed to make it work no problem in a different computer. The only difference being a RTX 2080Ti vs GTX1070Ti, but I guess this little program does not use GPU at all anyway.

OpenCV is the same on both computers too...so I ran out of ideas.

**Comment by auesro** [comment]
Also copying the Labeler file compiled on the working computer to the non-working computer results in the same behavior: everything works except no output is saved...

**Comment by SkepticRaven** [comment]
You're correct in assuming that it doesn't touch CUDA. That shouldn't be the cause.

I'm looking at the [function](https://github.com/KumarLabJax/MouseTrackingExtras/blob/b32500aa16dbbb73952ad5c79b30edbbc8322637/Watershed_Labeler/Watershed_Interactive_Release.cpp#L254) that writes the files and it looks as though if it gives you terminal feedback (stating the data being written), then writing the data didn't error.

Does the system have write permissions to the folder with the video?
Is there available drive space to write files?

**Comment by auesro** [comment]
It created the Reg, Seg, Ell folders so I assume permissions are not an issue.  And also space to spare...

Are there any accessory packages that the code would require for the saving? I dont see anything but Im no expert..

**Comment by SkepticRaven** [comment]
Opencv needs a png library to write pngs (which are pretty standard on systems now), but the ellipse fit text file uses base c++ file writers.

**Comment by auesro** [comment]
I understand that means nothing special. Is there an easy way to check that I have those libraries and writters installed?

**Comment by SkepticRaven** [comment]
```dpkg --search libpng``` or ```apt list -a -installed libpng*``` should return all installed png related libraries. On my system, I have libpng12 and libpng12-dev.

However, if you don't have ellipse fit files then it's unrelated to having these accessory packages. It's definitely an issue about the software not wanting to write to that folder rather than not knowing how to write to in the format.

Could you try having the video in a different folder? (If you have a different hard drive or flash drive, that might be a good test as well).
Is the name of the video causing issues?

**Comment by auesro** [comment]
Ok, so I tried the same movie file I was using at the home computer. The name is simply 'A.mp4'.
Copied to /home/user/Desktop
Copied to /home
Copied to /media (external USB pendrive)
Copied to /media (internal hard drive)
Same results: folders are created, but files are not output.
By the way, I forgot to mention (but I guess it is not connected), the -nf option was never working for me. Independently of the number I put there the program will continue until I press Q.

**Comment by SkepticRaven** [comment]
The last thing that I can think of is... is the terminal used to execute the program in the same folder as the video (fn parameter _doesn't_ have folders)? I haven't tested it with folders, but it looks like it would probably cause issues.

If it's not that, the only problem that seems to surface from other similar problems on the web appear to be a compiler-level issue, which would be really difficult to correct.

It does appear that during a re-write, I forgot to add back in the nf quit condition. That should be an easier fix that I'll push in the near future.

**Comment by auesro** [comment]
Well, you were exactly right!
Running the program in Terminal from the folder containing the Labeler file and containing the video: If you give the program the full path to the file `-fn=/home/user/bla/bla/bla/A.mp4` it will not save any output, if you give just `-fn=A.mp4` it will work as intended.
Thanks a lot Brian, case closed!

**Comment by auesro** [comment]
Oh, by the way, in case you want to add to the Documentation:
-It works with OpenCV 4.1.0 (latest version as of today)
-You dont need to compile from source, it is enough with sudo apt-get install libopencv-dev python3-dev (at least in Linux Mint Tessa). But you need to adapt the compilation command to point to the right folders in your system for the -I and -L arguments.
